# Generated by Django 3.0.6 on 2020-05-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=2000, verbose_name='Sobrenome')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
        ),
    ]
